### ISSUE TITLE
dictionary.txt construction broken by changes to rime/rime-cantonese

### ISSUE THREAD

**Issue by jlfwong** [CanCLID/to-jyutping#1]
Hi there!

I was looking at how the `dictionary.txt` file is constructed in this repository, and saw that it fetches https://raw.githubusercontent.com/rime/rime-cantonese/main/jyut6ping3.dict.yaml. It seems like the format of that file changed, however in https://github.com/rime/rime-cantonese/commit/69d7a236dda0a1e2d1687bc058f549b1dd481742 that file was split into many files. So now running `npm run preprocess` in this repository creates an empty `src/dictionary.txt`

**Comment by graphemecluster** [comment]
Thanks for the issue. However I am going to close it since we no longer uses `jyut6ping3.dict.yaml` after the major update. My apologies.
